server:
  port: 8080
spring:
  application:
    name: graalvm-native-example
  r2dbc:
    one:
      name: mysql1
      url: r2dbc:mysql://localhost:3306/local_test?serverZoneId=Asia/Shanghai
      username: root
      password: 123
    two:
      name: mysql2
      url: r2dbc:mysql://localhost:3306/local_test_2?serverZoneId=Asia/Shanghai
      username: root
      password: 123
  data:
    redis:
      one:
        host: 127.0.0.1
        port: 6379
        client-type: lettuce
      two:
        host: 127.0.0.1
        port: 6379
        client-type: lettuce